// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutContent: typeof import('./src/components/about/AboutContent.vue')['default']
    Articles: typeof import('./src/components/home/Articles.vue')['default']
    Category: typeof import('./src/components/aside/Category.vue')['default']
    CustomCate: typeof import('./src/components/category/CustomCate.vue')['default']
    Details: typeof import('./src/components/home/Details.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HotAriticles: typeof import('./src/components/aside/HotAriticles.vue')['default']
    MyBanner: typeof import('./src/components/MyBanner.vue')['default']
    MyFooter: typeof import('./src/components/MyFooter.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
